#!/usr/bin/env bash

if [[ "${1}" = 'impala-state-store' ]]; then
  # start impala-state-store
  sudo service impala-state-store start  
elif [[ "${1}" = 'impala-catalog' ]]; then
  # start impala-catalog
  sudo service impala-catalog start 
elif [[ "${1}" = 'impala-server' ]]; then
  # start impala-server
  sudo service impala-server start
else
  echo "Invalid command '${1}'" >&2
  exit 1
fi
